default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cookbook_dev

test:
  <<: *default
  database: cookbook_test

production:
  <<: *default
  database: cookbook_prod
